### ISSUE TITLE
Scoreboard does not display losses of each player

### ISSUE THREAD

**Issue by ry-prz** [tyheise/tictactoe#18]
From the requirement specification on the assignment document:

> Feature 2: add a scoreboard that keeps track of how many games were won, lost, tied by each player.

This to me implies it wants the losses of each player to be displayed. I know that this would be inferred by looking at the other player's wins, but we should probably add it in the scoreboard display to fit the requirement.

Thoughts?

**Comment by tyheise** [comment]
"Explicit is better than implicit." Good catch, Ryan!

**Comment by ry-prz** [comment]
Im on it!
